###
from ubuntu:18.04

LABEL maintainer="Red Cabbage"
LABEL VERSION="1.0" ARCHITECTURE="amd64"

RUN apt update && \
 apt -y install python3 \
                python3-pip \
                python3-venv  \
                git \
                vim   
                 

    

CMD ["/bin/bash"]

